# Generated by ChatGPT on 2026-02-08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_production_and_user_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='unique_key',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True, verbose_name='Уникальный ключ'),
        ),
        migrations.CreateModel(
            name='ProductionInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата использования')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invites', to='users.user', verbose_name='Кем создан')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invites', to='users.user', verbose_name='Кем использован')),
                ('production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='users.production', verbose_name='Производство')),
            ],
            options={
                'verbose_name': 'Инвайт производства',
                'verbose_name_plural': 'Инвайты производств',
            },
        ),
    ]
