# Generated by Django 5.1.1 on 2026-02-02 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
        ('sales', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_date', models.DateField(help_text='Дата, на которую проводится ревизия', verbose_name='Дата ревизии')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлена на обработку'), ('processing', 'В обработке'), ('completed', 'Завершена')], default='draft', max_length=20, verbose_name='Статус ревизии')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to=settings.AUTH_USER_MODEL, verbose_name='Автор ревизии (сотрудник)')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='sales.location', verbose_name='Точка производства')),
            ],
            options={
                'verbose_name': 'Ревизия',
                'verbose_name_plural': 'Ревизии',
                'ordering': ['-revision_date', 'location'],
            },
        ),
        migrations.CreateModel(
            name='RevisionIngredientItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Фактическое количество')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ingredient', verbose_name='Ингредиент')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_items', to='revisions.revision', verbose_name='Ревизия')),
            ],
            options={
                'verbose_name': 'Остаток ингредиента',
                'verbose_name_plural': 'Остатки ингредиентов',
            },
        ),
        migrations.CreateModel(
            name='RevisionProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_quantity', models.PositiveIntegerField(help_text='Из колонки "Количество" в Excel', verbose_name='Фактическое количество (штук)')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт (Номенклатура)')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='revisions.revision', verbose_name='Ревизия')),
            ],
            options={
                'verbose_name': 'Остаток продукта',
                'verbose_name_plural': 'Остатки продуктов',
            },
        ),
        migrations.CreateModel(
            name='RevisionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=3, help_text='Начальный - расход_на_продукцию + поступления', max_digits=10, verbose_name='Расчетный остаток')),
                ('actual_quantity', models.DecimalField(decimal_places=3, help_text='Прислали из ревизии ингредиентов', max_digits=10, verbose_name='Фактический остаток')),
                ('difference', models.DecimalField(decimal_places=3, help_text='Отрицательное число = недостача', max_digits=10, verbose_name='Разница (факт - ожидаемый)')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% отклонения')),
                ('status', models.CharField(choices=[('ok', '✅ Норма (0-3%)'), ('warning', '⚠️ Внимание (3-10%)'), ('critical', '🔴 Критично (>10%)')], max_length=20, verbose_name='Статус проблемы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ingredient', verbose_name='Ингредиент')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='revisions.revision', verbose_name='Ревизия')),
            ],
            options={
                'verbose_name': 'Отчет по ревизии',
                'verbose_name_plural': 'Отчеты по ревизиям',
                'ordering': ['-revision__revision_date'],
            },
        ),
        migrations.AddIndex(
            model_name='revision',
            index=models.Index(fields=['location', 'revision_date'], name='revisions_r_locatio_759a13_idx'),
        ),
        migrations.AddIndex(
            model_name='revision',
            index=models.Index(fields=['status'], name='revisions_r_status_7b1450_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='revision',
            unique_together={('location', 'revision_date')},
        ),
        migrations.AlterUniqueTogether(
            name='revisioningredientitem',
            unique_together={('revision', 'ingredient')},
        ),
        migrations.AlterUniqueTogether(
            name='revisionproductitem',
            unique_together={('revision', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='revisionreport',
            unique_together={('revision', 'ingredient')},
        ),
    ]
