# Generated by Django 5.1.1 on 2026-02-02 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название точки производства')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('code', models.CharField(help_text='Уникальный код для интеграции с кассой', max_length=20, unique=True, verbose_name='Код точки (из МойКассир)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Точка производства',
                'verbose_name_plural': 'Точки производства',
            },
        ),
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата поступления')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество поступило')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='products.ingredient', verbose_name='Ингредиент')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='sales.location', verbose_name='Точка производства')),
            ],
            options={
                'verbose_name': 'Поступление',
                'verbose_name_plural': 'Поступления',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Текущий остаток (штук)')),
                ('is_exceptional', models.BooleanField(default=False, help_text='Если отмечено — учитывать этот остаток в расчётах ревизии как ручной/исключительный', verbose_name='Исключительный остаток')),
                ('reason', models.TextField(blank=True, help_text='Пояснение, почему используется ручной остаток', verbose_name='Причина/комментарий')),
                ('recorded_at', models.DateTimeField(blank=True, help_text='Когда был зафиксирован этот остаток (ручной пересчёт)', null=True, verbose_name='Дата учёта')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='products.product', verbose_name='Продукт')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='sales.location', verbose_name='Точка производства')),
            ],
            options={
                'verbose_name': 'Остаток продукта',
                'verbose_name_plural': 'Остатки продуктов',
                'unique_together': {('product', 'location')},
            },
        ),
        migrations.CreateModel(
            name='IngredientInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Текущий остаток')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='products.ingredient', verbose_name='Ингредиент')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_inventories', to='sales.location', verbose_name='Точка производства')),
            ],
            options={
                'verbose_name': 'Остаток ингредиента',
                'verbose_name_plural': 'Остатки ингредиентов',
                'unique_together': {('ingredient', 'location')},
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата продажи')),
                ('moykassir_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID из МойКассир')),
                ('quantity', models.PositiveIntegerField(help_text='Целое число >= 0', verbose_name='Количество продано (штук)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales.location', verbose_name='Точка производства')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['location', 'date'], name='sales_sales_locatio_25c6a8_idx'), models.Index(fields=['product', 'date'], name='sales_sales_product_4dd10b_idx')],
            },
        ),
    ]
