# Generated by ChatGPT on 2026-02-08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_production_and_user_fields'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='users.production', verbose_name='Производство'),
        ),
    ]
