# Generated by ChatGPT on 2026-02-08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_production_and_user_fields'),
        ('products', '0002_recipe_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='users.production', verbose_name='Производство'),
        ),
        migrations.AddField(
            model_name='product',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.production', verbose_name='Производство'),
        ),
    ]
