# Generated by Django 5.1.1 on 2026-05-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_production_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
            ],
            options={
                'verbose_name': 'Новый рецепт',
                'verbose_name_plural': 'Новые рецепты',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
    ]
